AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Test template

Globals:
  Function:
    Timeout: 18
    Runtime: nodejs8.10
    Handler: index.handler
Resources:
  ApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: gateway
      StageName: dev
  SynchroniseLambda:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          FLASHDECK_TABLE_NAME:
            !Sub ${AWS::StackName}-flashdeck-table
          DYNAMODB_ENDPOINT: "http://localhost:8000"
          REGION: "eu-west-1"
      CodeUri: synchroniselambda/
      Runtime: nodejs8.10
      Role: 
        !GetAtt LambdaExecutionRole.Arn
      RestApiId: 
        !Ref ApiGateway
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            Path: /synchronise
            Method: any
  FlashDeckTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-flashdeck-table
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: lastModified
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: lastModified
          AttributeType: N
      GlobalSecondaryIndexes:
        - IndexName: last_modified_index
          KeySchema:
            - AttributeName: id
              KeyType: HASH
            - AttributeName: lastModified
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      BillingMode: PROVISIONED
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true